### DISCUSSION TITLE
spaCy project.yml script argument quoting

### DISCUSSION THREAD

**Discussion by jonbuffington** [explosion/spaCy#10434] [Help: Best practices]
I noticed that the second argument of a script line is automatically quoted when executed. The automatic quoting interferes with the shell recognizing the globpat.

E.g., Given the following `project.yml` fragment:

```yaml
commands:
- name: clean
  help: Remove intermediate files
  script:
  - rm -f corpus/*.spacy
```

execution using spaCy 3.2.2 yields:

```shell
$ python -m spacy project run clean

=================================== clean ===================================
Running command: rm -f 'corpus/*.spacy'
```

where the automatic quoting interferes with the shell matching the .spacy files in the corpus directory.

As a work-around, I used `sh -c`:

```yaml
- name: clean
  help: Remove intermediate files
  script:
  - sh -c "rm -f corpus/*.spacy"
```

Is there an option to disable `spacy project run`'s automatic second argument quoting?
