### DISCUSSION TITLE
Is it possible to pass nlp object to registry functions via config?

### DISCUSSION THREAD

**Discussion by kinghuang** [explosion/spaCy#12118] [Help: Coding & Implementations]
I'm using a [SpanRuler](https://spacy.io/api/spanruler) with a custom `spans_filter`. A registry function is used in the config to create the filter function.

```toml
[components.custom_span_ruler]
factory = "span_ruler"
spans_filter = {"@misc":"some_name.some_spans_filter.v1"}
```

```python
@registry.misc("some_name.some_spans_filter.v1")
def make_some_spans_filter():
    def some_spans_filter(
        existing_spans: Iterable[Span],
        new_spans: Iterable[Span],
        sequence_patterns: dict=sequence_patterns,
    ) -> List[Span]:
        return new_spans

    return some_spans_filter
```

Is there a way in the config to refer to the nlp (Language) object, so that I can pass it to the registry function as an argument on `make_some_spans_filter`? I tried looking at the [confection](https://github.com/explosion/confection) and [spacy](http://github.com/explosion/spaCy/) code, but couldn't tell if there was some magical variable or keyword that would provide such a reference (the `???` below).

```toml
[components.custom_span_ruler]
factory = "span_ruler"
spans_filter = {"@misc":"some_name.some_spans_filter.v1", "nlp": "???"}
```

```python
@registry.misc("some_name.some_spans_filter.v1")
def make_some_spans_filter(nlp: Language):
   …
```
