### DISCUSSION TITLE
misc registry (spacy version 3.6.1)

### DISCUSSION THREAD

**Discussion by TongmengXie** [explosion/spaCy#12971] [Help: Coding & Implementations] [answered]
# Error Info
```
RegistryError                             Traceback (most recent call last)
[<ipython-input-8-c525ef9d1c99>](https://localhost:8080/#) in <cell line: 2>()
      1 from spacy_llm.util import assemble
----> 2 nlp_falcon = assemble("/content/drive/MyDrive/WorkDir/Histo_link/model/base_config_llm.cfg")

12 frames
[/usr/local/lib/python3.10/dist-packages/spacy/util.py](https://localhost:8080/#) in get(cls, registry_name, func_name)
    161                     pass
    162             available = ", ".join(sorted(reg.get_all().keys())) or "none"
--> 163             raise RegistryError(
    164                 Errors.E893.format(
    165                     name=func_name, reg_name=registry_name, available=available

RegistryError: [E893] Could not find function 'spacy.FewShotReader.v1' in function registry 'misc'. If you're using a custom function, make sure the code is available. If the function is provided by a third-party package, e.g. spacy-transformers, make sure the package is installed in your environment.

Available names: spacy.CandidateBatchGenerator.v1, spacy.CandidateGenerator.v1, spacy.EmptyKB.v1, spacy.EmptyKB.v2, spacy.KBFromFile.v1, spacy.LookupsDataLoader.v1, spacy.LowercaseNormalizer.v1, spacy.StripNormalizer.v1, spacy.first_longest_spans_filter.v1, spacy.levenshtein_compare.v1, spacy.ngram_range_suggester.v1, spacy.ngram_suggester.v1, spacy.preset_spans_suggester.v1, spacy.prioritize_existing_ents_filter.v1, spacy.prioritize_new_ents_filter.v1
```

## How to reproduce the behaviour

```
from spacy_llm.util import assemble
nlp_falcon = assemble("/content/drive/MyDrive/WorkDir/Histo_link/model/base_config_llm.cfg")
```

base_config_llm.cfg:
```
[nlp]
lang = "en"
pipeline = ["llm"]

[components]

[components.llm]
factory = "llm"

[components.llm.task]
@llm_tasks = "spacy.SpanCat.v2"
# @llm_tasks = "spacy.NER.v2"
labels = ["INVENTOR", "ADDRESS"]
# labels = INVENTOR,ADDRESS

[components.llm.task.label_definitions]

INVENTOR = "The individual who created a patent or invention. This is typically a proper name like 'JOHN GNAGEE,' usually accompanied by terms like 'OF,' followed by an address."
ADDRESS = "The location where the inventor resides, often a series of words including street, city, and sometimes county, separated by commas or other punctuation. May appear in sequences like 'OF 6 LINGFIELD ROAD, WIMBLEDON IN THE COUNTY OF SURREY"

[components.llm.task.examples]
@misc = "spacy.FewShotReader.v1"
path = /content/drive/MyDrive/WorkDir/Histo_link/model/few_shot_NER.yml

[components.llm.model]
@llm_models = "spacy.Falcon.v1"
name = "falcon-rw-1b"
# @llm_models = "spacy.Dolly.v1"
# name = "dolly-v2-3b"
```
few_shot_NER.yml:
```
- text: PROVISIONAL SPECIFICATION.IMPROVEMENTS IN VAPOR CONDENSERS OR DEVAPORATORS.I, JOHN GNAGEE OF 6 LINGFIELD ROAD, WIMBLEDON IN THE COUNTY OF SURREY GENTLEMAN
  entities:
    INVENTOR:
      - JOHN GNAGEE
    ADDRESS:
      - 6 LINGFIELD ROAD, 
      - WIMBLEDON 
      - SURREY 
- text: PROVISIONAL SPECIFICATION.IMPROVEMENTS RELATING TO BUTTONHOLES IYEL3IN > 7 MATILDA SOPIIICA JONKS, SPINSTER OF LI LOUVAINE 1M ST. JOHNS HILL NEW WANDSWORTH LONDON S.W. I, THE ABOVENAMED
  entities:
    INVENTOR:
      - MATILDA SOPIIICA JONKS
    ADDRESS:
      - ST. JOHNS HILL 
      - NEW WANDSWORTH 
      - LONDON
```

## Environment
============================== Info about spaCy ==============================

spaCy version    3.6.1                         
Location         /usr/local/lib/python3.10/dist-packages/spacy
Platform         Colab: Linux-5.15.109+-x86_64-with-glibc2.35
Python version   3.10.12                       
Pipelines        en_core_web_md (3.6.0), en_core_web_sm (3.6.0)
