### DISCUSSION TITLE
Entity Linking with Wikipedia and Wikidata on spaCy v3.7

### DISCUSSION THREAD

**Discussion by RistovaIvona** [explosion/spaCy#13049] [Help: Coding & Implementations] [answered]
I'm planning to perform custom training with spaCy for entity linking using Wikidata. Could you provide guidance on creating a KnowledgeBase, especially since the latest spaCy version needs InMemoryLookupKB? I'm also considering refactoring the code in the current GitHub repository (https://github.com/explosion/projects/tree/master/nel-wikipedia) to match the latest version. Do you think this is a good approach, or is there a simpler way? Any helpful tips or tricks would be welcome.

**Comment by rmitsch** [comment, marked as answer]
Hi @RistovaIvona! `InMemoryLookupKB` is identical to the previous `KnowledgeBase` class - the renaming was done as part of a refactoring that will make knowledge bases more customizable and capable in spaCy v4.

Having said that, some resources that might be useful for you:
- [`wikid`](https://github.com/explosion/wikid) is a spaCy project for pulling Wikidata dumps, preprocessing and storing them in a SQLite database.
- The [EL benchmark project](https://github.com/explosion/projects/tree/v3/benchmarks/nel) leverages `wikid` to use Wikidata as knowledge base. The dataset used for training and evaluation is [Mewsli-9](https://paperswithcode.com/dataset/mewsli-9), but it should be easy enough to adjust the scaffolding to train with any other dataset.

In general I'd recommend adjusting the linked EL benchmark project - I think you'll have less work updating that one to your requirements than the (considerably older) `nel-wikipedia` project.

If you have any specific questions, feel free to drop them here.

**Reply by RistovaIvona** [reply]
Thank you for your answer; I really appreciate it. I have a couple of questions:

1. Initially, I create a KnowledgeBase. I tried doing it with 'wikid,' and it seems that everything is created successfully. I have the output folder, kb, nlp, descriptions.csv, and wiki.sqlite3 created. However, I encountered an error in the Bash shell at the end:
```
Inferring entity embeddings: 100%|##########| 38006/38006 [01:06<00:00, 572.20it/s]
Traceback (most recent call last):

  File "C:\Users\****\wikid\scripts\create_kb.py", line 98, in <module>
    typer.run(main)

  File "C:\Users\****\wikid\scripts\create_kb.py", line 93, in main
    csv_writer.writerow([qid, ent_desc])

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 46: character maps to <undefined>
```
What does this error mean? Do I have any issues, or not?

2. If I choose to use the EL benchmark project, will I need to work on a Linux OS?

**Reply by rmitsch** [reply]
1. Hm, that seems to be an encoding error. See https://stackoverflow.com/a/42495690, opening with `encoding="utf-8"` should do the trick. I pushed a [potential fix](https://github.com/explosion/wikid/pull/31) - pull from `main` and try again? 
2. Some auxiliary commands, especially fetching the Mewsli-9 dataset, don't work on Windows out of the box. You'd have to work around these issues, but the core of the project is OS-independent.

**Reply by RistovaIvona** [reply]
Thanks a lot for your support.
I've started implementing the EL benchmark project, and I wanted to ask if there's a way to use my own downloaded Wikipedia dataset without downloading it as a step in the project. If not, what machine type should I use so I can download the Wikipedia dataset without any filters?

**Reply by rmitsch** [reply]
- Yes, you can download your own Wikipedia/Wikidata dumps and store them in the `assets` directory.
- You can download the unfiltered Wiki dumps by setting `download_all_wiki_assets` to `"--extra"` in `project.yml` and running `spacy project run wikid_download_assets`.

**Reply by RistovaIvona** [reply]
Perfect, I did it. I put `"--extra"` in `project.yml` file and now the training is done.
My question now is, how can I use the trained model. I suppose that the model is in the `benchmarks/nel/training/mewsli_9/cg-default/model-best`.

I tried this:

```
import spacy
from spacy import displacy

nlp = spacy.load('/home/**/.ssh/projects/benchmarks/nel/training/mewsli_9/cg-default/model-best'')

# Example list of texts
text_list = ["Contrary to how McCarthy's defenders...."]

# Process each text in the list
for text in texts:
    doc = nlp2(text)
    
    # Print the detected entities along with start, end positions
    print("Text:", text)
    for ent in doc.ents:
        
        print(f"start: {ent.start}, end: {ent.end}, surface_form: {ent.text}, label: {ent.label_}, id: {ent.kb_id_}")

# Clean up
nlp.disable_pipes('ner')  # Disable the NER component if you don't need it for subsequent processing
```
And the output:
```
Text: Contrary to how McCarthy's defenders....
start: 3, end: 4, surface_form: McCarthy, label: PERSON, id: NIL
```
Is this correct?
Is it possible to get the QIDs and to have output like this:
`[16, 24, 'McCarthy', 'Q590790']`

**Reply by rmitsch** [reply]
You are using the model correctly. The `kb_id_` should contain the Wikidata QID, which it doesn't in this case. Try running your model with
`text_list = ["Contrary to how Kevin McCarthy's defenders...."]` and let me know how the output of your script looks like.

**Reply by RistovaIvona** [reply]
With this code:
```
import spacy
from spacy.tokens import Span

# Load custom-trained NER model
nlp = spacy.load('/home/**/.ssh/projects/benchmarks/nel/training/mewsli_9/cg-default/model-best')

# Example list of texts

text_list = ["Contrary to how McCarthy's defenders...."]

# Process each text in the list
for text in text_list:
    doc = nlp(text)
    print("Model output:", doc)

    # Print the detected entities along with start, end positions
    print("Text:", text)

    for ent in doc.ents:      
        print(f"start: {ent.start}, end: {ent.end}, surface_form: {ent.text}, label: {ent.label_}, id: {ent.kb_id_}")

# Clean up
nlp.disable_pipes('ner')  # Disable the NER component if you don't need it for subsequent processing
```
This is the output:
```
Model output: Contrary to how McCarthy's defenders....
Text: Contrary to how McCarthy's defenders....
start: 3, end: 4, surface_form: McCarthy, label: PERSON, id: NIL
```

**Reply by rmitsch** [reply]
Right, but my point was to run your script with this: `text_list = ["Contrary to how Kevin McCarthy's defenders...."]`. Note that this is a different text than the one you use. I'll follow up on why this change might be relevant for troubleshooting later.

**Reply by RistovaIvona** [reply]
Aha, I see. 
I did it and this is the output:
```
Model output: Contrary to how Kevin McCarthy's defenders....
Text: Contrary to how Kevin McCarthy's defenders....
start: 3, end: 5, surface_form: Kevin McCarthy, label: PERSON, id: NIL
```

**Reply by rmitsch** [reply]
Hm, that's unexpected. The reason I asked is that spaCy by default uses strict lexical matching to identify entity candidates, i. e. if your surface form is "McCarthy", there has to be an alias of "McCarthy" in the knowledge base. This can be modified, but would have explained the failure to produce a QID. I would have assumed that Kevin McCarthy produces results though.

Two more suggestions:
- Please provide the config you used to train your EL model.
- Look up whether "Kevin McCarthy" is actually in your KB (the .sqlite file).

**Reply by RistovaIvona** [reply]
This is what I have in the db for McCarthy (for Kevin McCarthy is empty):
![image](https://github.com/explosion/spaCy/assets/53267539/32e591c9-f2f9-492a-a7ea-73a336ece529)

**Reply by rmitsch** [reply]
To verify this is working, run your script with `text_list = ["Contrary to how Joe McCarthy's defenders...."]`?

**Reply by RistovaIvona** [reply]
This is the script: 
```
import spacy
from spacy.tokens import Span

# Load custom-trained NER model
nlp = spacy.load('/home/**/.ssh/projects/benchmarks/nel/training/mewsli_9/cg-default/model-best')

# Example list of texts

text_list = ["Contrary to how Joe McCarthy's defenders...."]

# Process each text in the list
for text in text_list:
    doc = nlp(text)
    print("Model output:", doc)

    # Print the detected entities along with start, end positions
    print("Text:", text)

    for ent in doc.ents:      
        print(f"start: {ent.start}, end: {ent.end}, surface_form: {ent.text}, label: {ent.label_}, id: {ent.kb_id_}")

# Clean up
nlp.disable_pipes('ner')  # Disable the NER component if you don't need it for subsequent processing

```
Here is the output: 
```
Model output: Contrary to how Joe McCarthy's defenders....
Text: Contrary to how Joe McCarthy's defenders....
start: 3, end: 6, surface_form: Joe McCarthy's, label: PERSON, id: NIL
```

**Reply by RistovaIvona** [reply]
When I try this as input text: 
`text_list = ["Contrary to how Joe McCarthy defenders...."]`

This is what I have as output:
```
Model output: Contrary to how Joe McCarthy defenders....
Text: Contrary to how Joe McCarthy defenders....
start: 3, end: 5, surface_form: Joe McCarthy, label: PERSON, id: Q332899
```

**Reply by rmitsch** [reply]
You don't need to share the script every time :slightly_smiling_face:  
In this case the `"'s"` isn't properly processed. Let's give this one more shot with `text_list = ["This is Joe McCarthy."]`.

**Reply by RistovaIvona** [reply]
Here is the output: 
```
Model output: This is Joe McCarthy.
Text: This is Joe McCarthy.
start: 2, end: 4, surface_form: Joe McCarthy, label: PERSON, id: Q332899
```

**Reply by RistovaIvona** [reply]
Why are there still missing entities even when I train on the entire Wikipedia dataset?

**Reply by rmitsch** [reply]
Alright, so we've verified that this works in general. Kevin McCarthy [is in Wikidata](https://www.wikidata.org/wiki/Q766866) though, so it's strange that you don't have his entry in your KB. How large is your KB? Maybe passing `--extra` didn't work properly and you ended up with the filtered/demo KB.

**Reply by RistovaIvona** [reply]
I am checking the KB from: `'/home/**/.ssh/projects/benchmarks/nel/wikid/output/en/kb/contents'` that is 46.8 MB, and `'/home/**/.ssh/projects/benchmarks/nel/wikid/output/en/kb/strings.json'` that is 12.5 MB.

**Reply by rmitsch** [reply]
What's the size of your DB file?

**Reply by RistovaIvona** [reply]
Hmm, it is just 98.2 MB.

**Reply by rmitsch** [reply]
Yeah, that's just the demo KB file (mostly entities for Wiki entries containing "New York" or "Boston"). 

The full DB after ingesting Wiki data is around 12 GB IIRC, and it takes the better part of a day to download and process that data. Can you share your `project.yml`?

**Reply by RistovaIvona** [reply]
It takes half a day, so that's why I am confused now. 
Here is the project.yml file.

```
title: 'NEL Benchmark'
description: "Pipeline for benchmarking NEL approaches (incl. candidate generation and entity disambiguation)."
spacy_version: ">=3.0.0,<3.6.0"
vars:
  run: "cg-default"
  language: "en"
  config: "nel.cfg"
  vectors_model: "en_core_web_lg"
  version: "0.0.5"
  dataset: "mewsli_9"
  gpu_id: ""
  download_all_wiki_assets: "--extra"  # "--extra" to download full Wiki dumps.
  filter: "True"  # Whether to only use parts of Wiki data and corpus containing filter terms.
  training_max_steps: 1000
  eval_highlight_metric: "F"  # one of ("F", "r", "p")

directories: ["assets", "training", "configs", "scripts", "corpora", "evaluation"]

workflows:
  all:
    - download_mewsli9
    - download_model
    - wikid_clone
    - preprocess
    - wikid_download_assets
    - wikid_parse
    - wikid_create_kb
    - parse_corpus
    - compile_corpora
    - train
    - evaluate
    - compare_evaluations
  training:
    - train
    - evaluate

commands:
  - name: download_mewsli9
    help: Download Mewsli-9 dataset.
    script:
      - bash scripts/datasets/download_mewsli-9.sh
    outputs:
      - assets/mewsli_9/raw

  - name: download_model
    help: "Download a model with pretrained vectors and NER component."
    script:
      - "python -m spacy download ${vars.vectors_model}"

  - name: wikid_clone
    help: Clone `wikid` to prepare Wiki database and `KnowledgeBase`.
    script:
      - git clone https://github.com/explosion/wikid.git --branch main
      - pip install -r wikid/requirements.txt
    outputs:
      - wikid

  - name: preprocess
    help: Preprocess and clean corpus data.
    script:
      - "env PYTHONPATH=. python ./scripts/clean_data.py ${vars.dataset} ${vars.language}"
    deps:
      - "assets/${vars.dataset}/raw"
    outputs:
      - "assets/${vars.dataset}/clean"

  - name: wikid_download_assets
    help: "Download Wikipedia dumps. This can take a long time if you're not using the filtered dumps!"
    script:
      - "spacy project assets wikid ${vars.download_all_wiki_assets}"
    outputs:
      - "wikid/assets/"

  - name: wikid_parse
    help: "Parse Wikipedia dumps. This can take a long time if you're not using the filtered dumps!"
    script:
      - "spacy project run parse wikid --vars.language ${vars.language} --vars.filter True"
    outputs:
      - "wikid/output/${vars.language}/wiki.sqlite3"

  - name: wikid_create_kb
    help: "Create the knowledge base and write it to file."
    script:
      - "spacy project run create_kb wikid --vars.language ${vars.language} --vars.vectors_model ${vars.vectors_model}"
    deps:
      - "wikid/output/${vars.language}/wiki.sqlite3"
    outputs_no_cache:
      - "wikid/output/${vars.language}/kb"
      - "wikid/output/${vars.language}/nlp"

  - name: parse_corpus
    help: "Parse corpus to generate entity and annotation lookups used for corpora compilation."
    script:
      - "env PYTHONPATH=. python ./scripts/parse_corpus.py ${vars.dataset} ${vars.language}"
    deps:
      - "assets/${vars.dataset}/clean"
      - "wikid/output/${vars.language}/wiki.sqlite3"
    outputs:
      - "assets/${vars.dataset}/entities.pkl"
      - "assets/${vars.dataset}/entities_failed_lookup.pkl"
      - "assets/${vars.dataset}/annotations.pkl"

  - name: compile_corpora
    help: "Compile corpora, separated in train/dev/test sets."
    script:
      - "env PYTHONPATH=. python ./scripts/compile_corpora.py ${vars.dataset} ${vars.language} ${vars.filter}"
    deps:
      - "assets/${vars.dataset}/entities.pkl"
      - "assets/${vars.dataset}/entities_failed_lookups.pkl"
      - "assets/${vars.dataset}/annotations.pkl"
      - "wikid/output/${vars.language}/kb"
      - "wikid/output/${vars.language}/nlp"
      - "configs/datasets.yml"
    outputs:
      - "corpora/${vars.dataset}/train.spacy"
      - "corpora/${vars.dataset}/dev.spacy"
      - "corpora/${vars.dataset}/test.spacy"

  - name: train
    help: "Train a new Entity Linking component. Pass --vars.gpu_id GPU_ID to train with GPU. Training with some datasets may take a long time!"
    script:
      - "bash scripts/train.sh ${vars.dataset} '${vars.run}' ${vars.language} ${vars.config} ${vars.training_max_steps} ${vars.gpu_id}"
    outputs:
      - "training/${vars.dataset}/${vars.run}"
    deps:
      - "wikid/output/${vars.language}/kb"
      - "wikid/output/${vars.language}/nlp"
      - "corpora/${vars.dataset}/train.spacy"
      - "corpora/${vars.dataset}/dev.spacy"

  - name: evaluate
    help: "Evaluate on the test set."
    script:
      - "env PYTHONPATH=. python ./scripts/evaluate.py ${vars.dataset} '${vars.run}' ${vars.language}"
    deps:
      - "training/${vars.dataset}/${vars.run}/model-best"
      - "wikid/output/${vars.language}/nlp"
      - "corpora/${vars.dataset}/dev.spacy"
    outputs:
      - "evaluation/${vars.dataset}"

  - name: compare_evaluations
    help: "Compare available set of evaluation runs."
    script:
      - "env PYTHONPATH=. python ./scripts/compare_evaluations.py ${vars.dataset} ${vars.language} --highlight-criterion ${vars.eval_highlight_metric}"
    deps:
      - "evaluation/${vars.dataset}"

  - name: delete_wiki_db
    help: "Deletes SQLite database generated in step wiki_parse with data parsed from Wikidata and Wikipedia dump."
    script:
      - "rm -f wikid/output/${vars.language}/wiki.sqlite3"
    deps:
      - "wikid/output/${vars.language}/wiki.sqlite3"

  - name: clean
    help: "Remove intermediate files for specified dataset and language (excluding Wiki resources and database)."
    script:
      - "rm -rf training/${vars.dataset}"
      - "rm -rf corpora/${vars.dataset}"
      - "rm -rf assets/${vars.dataset}"
      - "rm -rf evaluation/${vars.dataset}"
      - "rm -rf wikid/output/${vars.language}"
```
