### DISCUSSION TITLE
Training a new (or existing) model with a new entity

### DISCUSSION THREAD

**Discussion by rshahrabani** [explosion/spaCy#13083] [Help: Model Advice] [answered]
Hi,
I'm new to model training and would appreciate any tips/guidance on how to accomplish the below:

I would like to add a new entity to the NER of a new or existing model. We'll call this entity EPS.

a) firstly, do you recommend creating a new model from scratch or updating the existing model? (we would like to use the large English model). Can you give me a code snippet of how this can be done?

b) I noticed a lot of examples in [pipelines](https://github.com/explosion/projects/tree/v3/pipelines), among them ner_demo, ner_demo_replace and ner_demo_update. I could not figure out how to use these templates - can you provide some instructions on how to modify and run these project? Also, which one of the above projects do you recommend using for adding a new NER type?

c) lastly, do you recommend using the templates in b) or training the model in some other way?

Thanks for your help.
Ronny

**Comment by shadeMe** [comment, marked as answer]
While you can update an existing model to predict new entity types ([this demo project](https://github.com/explosion/projects/tree/v3/pipelines/ner_demo_update) does just that), it can be tricky to train it in such a way that the performance on existing entities doesn't suffer. 

So, it's usually easier to just train the model from scratch. If you are in need of training data, you could use the English model to predict the existing labels for raw text. These predictions can then be combined with the training data for the new labels to train the new model.

The example pipelines are implemented as spaCy Projects - the [documentation](https://spacy.io/usage/projects) goes over how they work.

**Comment by rshahrabani** [comment]
Madeesh, thanks for your informative reply.

I had a question with regards to the pipelines/ner_demo project which I am
using to train a model with a new NER type:

The workflows section in the project.yml file runs the train command and
the train-with-vectors command is commented out. Can you explain the
difference between the two and when I should use either one:

workflows:
  all:
...
    - train
    # - train-with-vectors
...

Thanks.

**Reply by svlandeg** [reply]
You basically have to pick one. Their definitions are further down in the yaml file:

```
- name: "train"
    help: "Train the NER model"
    script:
      - "python -m spacy train configs/config.cfg --output training/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --training.eval_frequency 10 --training.patience 50 --gpu-id ${vars.gpu_id}"


  - name: "train-with-vectors"
    help: "Train the NER model with vectors"
    script:
      - "python -m spacy train configs/config.cfg --output training/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --training.eval_frequency 10 --training.patience 50 --gpu-id ${vars.gpu_id} --initialize.vectors ${vars.vectors_model} --components.tok2vec.model.embed.include_static_vectors true"
```
As you can see, the `train-with-vectors` command adds an `--initialize.vectors` option that takes the vectors from a given `vectors_model`, in this case `en_core_web_md`, to initialize the new model you're starting to train from scratch. These vectors will be used by the embedding layer of the `tok2vec` component. This tok2vec component is a machine learning component that learns how to produce suitable (dynamic) vectors for tokens. It does this by looking at lexical attributes of the token, but may also include the static vectors of the token that you provided upon initialization, basically jump starting its modeling capacity.
