### DISCUSSION TITLE
W&B sweep showing a null metric value

### DISCUSSION THREAD

**Discussion by martyna-spyra** [explosion/spaCy#13256] [Help: Coding & Implementations]
Hi, I'm trying to use wandb sweeps to tune hyperparameters of my spancat model. I tried both approaches demonstrated in this [project](https://github.com/explosion/projects/tree/v3/integrations/wandb/scripts) but no matter what metric I enter in my sweep.yml file, it doesn't seem to be detected by wandb and appears as null in the dashboard: 
![image](https://github.com/explosion/spaCy/assets/147500605/d0768829-9f3e-4d44-9047-9bd8f4c3e597)
This is my sweep.yml:
```
command:
  - ${env}
  - ${interpreter}
  - ./sweeps_using_config.py
  - ./config_for_hpo.cfg
  - ./train

method: random
metric: 
  name: spans_sc_f
  goal: maximize

parameters:
  components.spancat.suggester.max_size:
    values:
    - 8
    - 13
    - 18
  training.dropout:
    distribution: uniform
    max: 0.5
    min: 0.05
  training.optimizer.learn_rate:
    distribution: uniform
    max: 0.01
    min: 0.001
```
