### DISCUSSION TITLE
ValueError: [E002] Can't find factory for 'relation_extractor' for language German (de).

### DISCUSSION THREAD

**Discussion by JRE-joe** [explosion/spaCy#7274] [Help: Coding & Implementations] [answered]
I've come across the issue:
ValueError: [E002] Can't find factory for 'relation_extractor' for language German (de). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

I've added the Custom Component Relation_Extractor from the SpaCy Projects to my NER Pipline.

This is my .cfg-file:
```
[paths]
ner_train = ""
ner_dev = ""
ner_vectors = null

init_tok2vec = null

rel_train = ""
rel_dev = ""
rel_raw = null

[system]
gpu_allocator = null
ner_seed = 0
rel_seed = 342

[nlp]
lang = "de"
pipeline = ["tok2vec","ner","relation_extractor"]
batch_size = 1000
disabled = []
before_creation = null
after_creation = null
after_pipeline_creation = null
tokenizer = {"@tokenizers":"spacy.Tokenizer.v1"}

[components]

[components.tok2vec]
factory = "tok2vec"

[components.tok2vec.model]
@architectures = "spacy.Tok2Vec.v2"

[components.tok2vec.model.embed]
@architectures = "spacy.MultiHashEmbed.v1"
width = ${components.tok2vec.model.encode.width}
attrs = ["NORM", "PREFIX", "SUFFIX", "SHAPE"]
rows = [2000,1000,1000,1000]
include_static_vectors = false

[components.tok2vec.model.encode]
@architectures = "spacy.MaxoutWindowEncoder.v2"
width = 128
depth = 6       
window_size = 1
maxout_pieces = 3

[components.ner]
factory = "ner"
moves = null
update_with_oracle_cut_size = 100

[components.ner.model]
@architectures = "spacy.TransitionBasedParser.v2"
state_type = "ner"
extra_state_tokens = false
hidden_width = 64
maxout_pieces = 2
use_upper = true
nO = null

[components.ner.model.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}
upstream = "*"

[components.relation_extractor]
factory = "relation_extractor"
threshold = 0.5

[components.relation_extractor.model]
@architectures = "rel_model.v1"

[components.relation_extractor.model.create_instance_tensor]
@architectures = "rel_instance_tensor.v1"

[components.relation_extractor.model.create_instance_tensor.tok2vec]
@architectures = "spacy.Tok2VecListener.v1"
width = ${components.tok2vec.model.encode.width}

[components.relation_extractor.model.create_instance_tensor.pooling]
@layers = "reduce_mean.v1"

[components.relation_extractor.model.create_instance_tensor.get_instances]
@misc = "rel_instance_generator.v1"
max_length = 100

[components.relation_extractor.model.classification_layer]
@architectures = "rel_classification_layer.v1"
nI = null
nO = null

[corpora]

[corpora.ner]

[corpora.ner.dev]
@readers = "spacy.Corpus.v1"
path = ${paths.ner_dev}
max_length = 0
gold_preproc = false
limit = 0
augmenter = null

[corpora.ner.train]
@readers = "spacy.Corpus.v1"
path = ${paths.ner_train}
max_length = 2000
gold_preproc = false
limit = 0
augmenter = null

[corpora.rel]

[corpora.rel.train]
@readers = "Gold_ents_Corpus.v1"
file = ${paths.rel_train}

[corpora.rel.dev]
@readers = "Gold_ents_Corpus.v1"
file = ${paths.rel_dev}

[training]

[training.ner]
dev_corpus = "corpora.ner.dev"
train_corpus = "corpora.ner.train"
seed = ${system.ner_seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600
max_epochs = 0
max_steps = 20000
eval_frequency = 200
frozen_components = []
before_to_disk = null

[training.ner.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2
get_length = null

[training.ner.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001
t = 0.0

[training.ner.logger]
@loggers = "spacy.ConsoleLogger.v1"
progress_bar = false

[training.ner.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.ner.score_weights]
ents_per_type = null
ents_f = 1.0
ents_p = 0.0
ents_r = 0.0

[training.rel]
seed = ${system.rel_seed}
gpu_allocator = ${system.gpu_allocator}
dropout = 0.1
accumulate_gradient = 1
patience = 1600000
max_epochs = 0
max_steps = 10000
eval_frequency = 500
frozen_components = []
dev_corpus = "corpora.rel.dev"
train_corpus = "corpora.rel.train"
before_to_disk = null
logger = {"@loggers":"spacy.ConsoleLogger.v1"}

[training.rel.batcher]
@batchers = "spacy.batch_by_words.v1"
discard_oversize = false
tolerance = 0.2

[training.rel.batcher.size]
@schedules = "compounding.v1"
start = 100
stop = 1000
compound = 1.001

[training.rel.optimizer]
@optimizers = "Adam.v1"
beta1 = 0.9
beta2 = 0.999
L2_is_weight_decay = true
L2 = 0.01
grad_clip = 1.0
use_averages = false
eps = 0.00000001
learn_rate = 0.001

[training.score_weights]
rel_micro_p = 0.0
rel_micro_r = 0.0
rel_micro_f = 1.0

[initialize]

[initialize.ner]
vectors = "de_core_news_lg"
init_tok2vec = ${paths.init_tok2vec}
vocab_data = null
lookups = null
before_init = null
after_init = null

[initialize.relation_extractor]

[initialize.components]

[initialize.tokenizer]
```

And the Relation Extraction Component is from https://github.com/explosion/projects/tree/v3/tutorials/rel_component
I can't manage to find a reasonable solution to my issue.

**Comment by adrianeboyd** [comment]
Have you included the code that defines this component using the `--code` argument with your `spacy train` command?

See how it's included with `-c` (short for `--code`) in the linked project:

https://github.com/explosion/projects/blob/fdd9823599d7c298d2bc824f2e67b2a5fe904e99/tutorials/rel_component/project.yml#L53

**Comment by JRE-joe** [comment]
The Code for the custom_functions.py is included in the SpaCy train command.

the project .yml is:

```
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  # NER Component VARS
  config: "configs/tok2vec.cfg"
  ner_train_annotations: "assets/train/NER_train.jsonl"
  ner_dev_annotations: "assets/dev/NER_dev.jsonl"
  ner_eval_annotations: "assets/eval/NER_all_eval.jsonl"
  ner_train_file: "corpus/train.ner.spacy" # training data in .spacy binary format
  ner_dev_file: "corpus/dev.ner.spacy" # dev set for the f-score,
  ner_test_file: "corpus/test.ner.spacy" # eval set (held back from training)
  lang: "de"
  gpu: -1
  # Relation Component VARS
  rel_train_annotations: "assets/train/REL_train.jsonl"
  rel_dev_annotations: "assets/dev/REL_dev.jsonl"
  rel_eval_annotations: "assets/eval/REL_all_eval.jsonl"
  tok2vec_config: "configs/rel_tok2vec.cfg"
  trf_config: "configs/rel_trf.cfg"
  
  rel_train_file: "data/train.rel.spacy" # training set to train the
  rel_dev_file: "data/dev.rel.spacy" # dev set for the f-score,
  rel_test_file: "data/test.rel.spacy" # eval set (held back)
  rel_trained_model: "training/model-best"

remotes:
  default: gs://galaxy-state/spacy-v3-benchmarks

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories:
  ["assets", "training", "configs", "metrics", "corpus", "scripts", "data"]

assets:
  - dest: ${vars.ner_train_annotations}
    description: "Gold-standard NER annotations created with Prodigy"
  - dest: ${vars.ner_dev_annotations}
    description: "Gold-standard NER  annotations created with Prodigy"
  - dest: ${vars.ner_eval_annotations}
    description: "Gold-standard NER annotations created with Prodigy"
  - dest: ${vars.rel_train_annotations}
    description: "Gold-standard REL annotations created with Prodigy"
  - dest: ${vars.rel_dev_annotations}
    description: "Gold-standard REL annotations created with Prodigy"
  - dest: ${vars.rel_eval_annotations}
    description: "Gold-standard REL annotations created with Prodigy"

workflows:
  all:
    - corpus
    - train_ner
    - ner_evaluate
    - data
    - train_cpu_rel
    - rel_evaluate

commands:
  - name: init-config
    help: "Generate a default German NER config"
    script:
      - "python -m spacy init config --lang de --pipeline ner --optimize efficiency -C ${vars.config}"

  - name: corpus
    help: "Convert the data to spaCy's format"
    # Make sure we specify the branch in the command string, so that the
    # caching works correctly.
    script:
      - "python ./scripts/preprocess.py ${vars.ner_train_annotations} ${vars.ner_train_file}"
      - "python ./scripts/preprocess.py ${vars.ner_dev_annotations} ${vars.ner_dev_file}"
      - "python ./scripts/preprocess.py ${vars.ner_eval_annotations} ${vars.ner_test_file}"

    deps:
      - ${vars.ner_train_annotations}
      - ${vars.ner_dev_annotations}
      - ${vars.ner_eval_annotations}
    outputs:
      - ${vars.ner_train_file}
      - ${vars.ner_dev_file}
      - ${vars.ner_test_file}

  - name: train_ner
    help: "Train the full pipeline"
    script:
      - "python -m spacy train ${vars.config} --output training/ --gpu-id ${vars.gpu} --paths.ner_train ${vars.ner_train_file} --paths.ner_dev ${vars.ner_dev_file}"
    deps:
      - ${vars.ner_train_file}
      - ${vars.ner_dev_file}
      - ${vars.config}
    outputs:
      - "training/model-best"

  - name: ner_evaluate
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy ner_evaluate ./training/model-best ${vars.ner_test_file} --output ./metrics/${vars.config}.json --gpu-id ${vars.gpu}"
    deps:
      - "training/model-best"
      - ${vars.ner_test_file}
    outputs:
      - "metrics/${vars.config}.json"

  - name: "data"
    help: "Parse the gold-standard annotations from the Prodigy annotations."
    script:
      - "python ./scripts/rel_parse_data.py ${vars.rel_train_annotations} ${vars.rel_dev_annotations} ${vars.rel_eval_annotations} ${vars.rel_train_file} ${vars.rel_dev_file} ${vars.rel_test_file}"
    deps:
      - ${vars.rel_train_annotations}
      - ${vars.rel_dev_annotations}
      - ${vars.rel_eval_annotations}
    outputs:
      - ${vars.rel_train_file}
      - ${vars.rel_dev_file}
      - ${vars.rel_test_file}

  - name: "train_cpu_rel"
    help: "Train the REL model on the CPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.tok2vec_config} --output training --paths.rel_train ${vars.rel_train_file} --paths.rel_dev ${vars.rel_dev_file} -c ./scripts/rel_custom_functions.py"
    deps:
      - ${vars.rel_train_file}
      - ${vars.rel_dev_file}
    outputs:
      - ${vars.rel_trained_model}

  - name: "train_gpu_rel"
    help: "Train the REL model with a Transformer on a GPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.trf_config} --output training --paths.rel_train ${vars.rel_train_file} --paths.rel_dev ${vars.rel_dev_file} -c ./scripts/rel_custom_functions.py --gpu-id 0"
    deps:
      - ${vars.rel_train_file}
      - ${vars.rel_dev_file}
    outputs:
      - ${vars.rel_trained_model}

  - name: "rel_evaluate"
    help: "Apply the best model to new, unseen text, and measure accuracy at different thresholds."
    script:
      - "python ./scripts/rel_evaluate.py ${vars.rel_trained_model} ${vars.rel_test_file} True"
    deps:
      - ${vars.rel_trained_model}
      - ${vars.rel_test_file}

  - name: "clean"
    help: "Remove intermediate files to start data preparation and training from a clean slate."
    script:
      - "rm -rf data/*"
      - "rm -rf training/*"
      - "rm -rf metrics/*"
      - "rm -rf corpus/*"
```
