### DISCUSSION TITLE
How to retrain the NER and Relational model from last checkpoint?

### DISCUSSION THREAD

**Discussion by karndeepsingh** [explosion/spaCy#9725] [Help: Coding & Implementations] [answered]
Hi, 
I have to train 15000 sentences for NER and the RELATIONAL model. I am planning to train it on 11GB GPU batch-wise. So, I can retrain the model always from the last checkpoint or best weights.

Thanks

**Comment by ljvmiranda921** [comment, marked as answer]
Hi @karndeepsingh ,

When you first train via spaCy, you'd always get the `model-best` and `model-last` in the output directory that you supplied.  If you want to resume training from them, you can supply their paths to the `source` parameter of your components in the [configuration file](https://spacy.io/usage/training#config). Something like this:

```toml
[components.ner]
source = "./output/model-last"  # or model-best

[components.tok2vec]
source = "./output/model-last"  # or model-best
```

Note that, it won't always be 100% equivalent because the rest of the training settings (like the optimizer, batcher, etc.) will be reset.
