### ISSUE TITLE
Citing spaCy

### ISSUE THREAD

**Issue by erip** [explosion/spaCy#10612]
I'm trying to cite spaCy and have tried converting the CITATION.cff to a bibtex entry using [cffconvert](https://github.com/citation-file-format/cff-converter-python). It seems like the included file doesn't pass validation:

```
jsonschema.exceptions.ValidationError: 'authors' is a required property

// ...

On instance:
    {'cff-version': '1.2.0',
     'preferred-citation': {'authors': [{'family-names': 'Honnibal',
                                         'given-names': 'Matthew'},
                                        {'family-names': 'Montani',
                                         'given-names': 'Ines'},
                                        {'family-names': 'Van Landeghem',
                                         'given-names': 'Sofie'},
                                        {'family-names': 'Boyd',
                                         'given-names': 'Adriane'}],
                            'doi': '10.5281/zenodo.1212303',
                            'message': 'If you use spaCy, please cite it '
                                       'as below.',
                            'title': 'spaCy: Industrial-strength Natural '
                                     'Language Processing in Python',
                            'type': 'article',
                            'year': 2020}}
```

When I reformat a bit, the following CITATION.cff validates:

```yaml
cff-version: 1.2.0
type: software
message: "If you use spaCy, please cite it as below."
authors:
  - family-names: "Honnibal"
    given-names: "Matthew"
  - family-names: "Montani"
    given-names: "Ines"
  - family-names: "Van Landeghem"
    given-names: "Sofie"
  - family-names: "Boyd"
    given-names: "Adriane"
title: "spaCy: Industrial-strength Natural Language Processing in Python"
doi: "10.5281/zenodo.1212303"
```

with the following bibtex entry:

```
@misc{YourReferenceHere,
author = {Honnibal, Matthew and Montani, Ines and Van Landeghem, Sofie and Boyd, Adriane},
doi = {10.5281/zenodo.1212303},
title = {spaCy: Industrial-strength Natural Language Processing in Python}
}
```

Do you have recommendations about how to appropriately convert the included .cff to bibtex? If not, is this included bibtex entry reasonable?
