### ISSUE TITLE
spacy[cuda] v3.8 incompatible with spacy_models

### ISSUE THREAD

**Issue by shenpengfii** [explosion/spaCy#13837]
# Bug Description

Installing latest SpaCy for GPU and spacy_models the way [SpaCy installation page](https://spacy.io/usage) tells is impossible to be done, as `cupy-cuda12x 12.3.0` requires `numpy<1.29,>=1.20`, but `spacy-pkuseg<2.0.0,>=1.0.0` requires `numpy<3.0.0,>=2.0.0`.

# Reproducing Step

```bash
$ uv run -- spacy download zh_core_web_sm
```
```
Collecting zh-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.8.0/zh_core_web_sm-3.8.0-py3-none-any.whl (48.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 MB 5.6 MB/s eta 0:00:00
Collecting spacy-pkuseg<2.0.0,>=1.0.0 (from zh-core-web-sm==3.8.0)
  Using cached spacy_pkuseg-1.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: srsly<3.0.0,>=2.3.0 in ./.venv/lib/python3.12/site-packages (from spacy-pkuseg<2.0.0,>=1.0.0->zh-core-web-sm==3.8.0) (2.5.1)
Collecting numpy<3.0.0,>=2.0.0 (from spacy-pkuseg<2.0.0,>=1.0.0->zh-core-web-sm==3.8.0)
  Using cached numpy-2.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: catalogue<2.1.0,>=2.0.3 in ./.venv/lib/python3.12/site-packages (from srsly<3.0.0,>=2.3.0->spacy-pkuseg<2.0.0,>=1.0.0->zh-core-web-sm==3.8.0) (2.0.10)
Using cached spacy_pkuseg-1.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
Using cached numpy-2.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (16.6 MB)
Installing collected packages: numpy, spacy-pkuseg, zh-core-web-sm
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
```
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 12.3.0 requires numpy<1.29,>=1.20, but you have numpy 2.3.1 which is incompatible.
```

# System Info

- My `UV` venv configuration:
```toml
[project]
name = "text-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "ipykernel>=6.29.5",
    "pip>=25.1.1",
    "python-dotenv>=1.1.0",
    "seaborn>=0.13.2",
    "spacy[cuda12x]>=3.8.7",
]
```

- My System: Ubuntu 24.04 WSL
```bash
$ cat /proc/version 
Linux version 6.6.87.1-microsoft-standard-WSL2 (root@af282157c79e) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP PREEMPT_DYNAMIC Mon Apr 21 17:08:54 UTC 2025
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble
```
