### ISSUE TITLE
PCF python app deployment SpaCy install error code -9

### ISSUE THREAD

**Issue by zhangyilun** [explosion/spaCy#3935]
I'm deploying an app on PCF (Pivotal Cloud Foundry) that uses SpaCy and I'm having error when install SpaCy.

The manifest file is:

```
applications:
- name: xxxxx
  instances: 1
  memory: 2048MB
  disk_quota: 2048MB
  command: python app.py
  buildpack: python_buildpack
  stack: cflinuxfs3
  timeout: 180
```

The error I'm getting is:

> Command "/tmp/contents587794960/deps/0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ralx3p8i/spacy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sx4g4727/install-record.txt --single-version-externally-managed --compile" failed with error code -9 in /tmp/pip-install-ralx3p8i/spacy/

I have seen others reporting this error but it was due to Python version, but mine's different (unless PCF is messing things up).

I was able to deploy exactly the same app on Heroku with no above error.

## Your Environment
* Operating System: Ubuntu 18.04 (on PCF)
* Python Version Used: 3.6.8
* spaCy Version Used: 2.0.12
