### ISSUE TITLE
displacy-ent demo color bug

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spaCy#4277]
When I visit the website of the [displaCy demo](https://explosion.ai/demos/displacy-ent), I and I scroll down to see the code below the *displaCy Named Entity Visualizer* heading, some text seems to be missing. In reality, the color is simply set to the same color as the background. Specifically, this is the culprit

```css
[data-demo=displacy-ent] .d-wrapper code {
    color: #1e1935;
}
```

When removing this style, the code is nice and white-ish.

I could not find the code to the demo in this repo, so I just filed an issue here.
