### ISSUE TITLE
Config overrides not working for spaCy project workflows

### ISSUE THREAD

**Issue by paulrinckens** [explosion/spaCy#8883]
## How to reproduce the behaviour
Overwriting config variables (either via additional command line arguments or via the env var SPACY_CONFIG_OVERRIDES) works well when executing individual spaCy project commands but does not get propagated when executing entire workflows. 

project.yml
````yaml
vars: 
  myvar: "a"
workflows:
  all:
    - step
commands:
  step:
    - echo ${vars.myvar}
````

When running the individual command the var is overwritten
````
python -m spacy project run step . --vars.myvar b
>>> b
````

but when running the workflow the override does not get propagated to the commands
````
python -m spacy project run all . --vars.myvar b
>>> a
````

## Your Environment
- **spaCy version:** 3.1.1
- **Platform:** macOS-11.4-x86_64-i386-64bit
- **Python version:** 3.9.4
- **Pipelines:** fr_core_news_md (3.1.0)
